export interface Comment {
    id: number;
    name: string;
    text: string;
  }
  
  export const comments: Comment[] = [
    {
      id: 1,
      name: "Comment 1",
      text: "THIS IS THE DESCRIPTION OF THE COMMENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. ",
    },
    {
      id: 2,
      name: "Comment 2",
      text: "This is the description of the comment: Nothing"
    },
    {
      id: 3,
      name: "Comment 3",
      text: "THIS IS THE DESCRIPTION OF THE COMMENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. ",
    },
    {
      id: 4,
      name: "Comment 4",
      text: "THIS IS THE DESCRIPTION OF THE COMMENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. ",
    },
    {
      id: 5,
      name: "Comment 5",
      text: "THIS IS THE DESCRIPTION OF THE COMMENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. ",
    },
    {
      id: 6,
      name: "Comment 6",
      text: "THIS IS THE DESCRIPTION OF THE COMMENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. ",
    },
    {
      id: 7,
      name: "Comment 7",
      text: "THIS IS THE DESCRIPTION OF THE COMMENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. ",
    },
    {
      id: 8,
      name: "Comment 8",
      text: "THIS IS THE DESCRIPTION OF THE COMMENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. ",
    },
    {
      id: 9,
      name: "Comment 9",
      text: "THIS IS THE DESCRIPTION OF THE COMMENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. ",
    },
    {
      id: 10,
      name: "Comment 10",
      text: "THIS IS THE DESCRIPTION OF THE COMMENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. >",
    },
    {
      id: 11,
      name: "Comment 11",
      text: "THIS IS THE DESCRIPTION OF THE COMMENT: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lorem ante, rutrum sit amet iaculis nec, maximus sed risus. Vivamus volutpat sollicitudin venenatis. Morbi in condimentum nunc, ac tempus augue. Ut pulvinar, dui ac vestibulum mattis, nulla est cursus nisl, in elementum urna ex eu purus. Cras mollis augue at justo vulputate, quis feugiat urna efficitur. Ut sit amet molestie ante. Vivamus semper, nisi id fringilla dictum, elit tellus egestas leo, sit amet dictum eros arcu ut est. Proin vel fermentum leo, at varius ipsum. Donec porttitor felis vel iaculis vulputate. Morbi gravida molestie urna non facilisis. Etiam risus eros, finibus quis iaculis quis, pulvinar ac ex. >",
    },
  ];
  